* Packages for working with paranthesis
  + [[https://github.com/Fuco1/smartparens][smartparens]] - A very useful package for working with parenthesis. Alongwith providing
  regular features like autopairing, it also provides function for naviagation and
  manipulation of parenthesis. However, python support is somewhat lacking.
  + [[https://github.com/capitaomorte/autopair][autopairs]] - Package for automatically pairing braces and quotes. Has better support
  python.

  #+begin_src emacs-lisp
    (defvar my-paranthesis-packages
      '(autopair
        smartparens))

    (el-get 'sync my-paranthesis-packages)

    (smartparens-global-mode t)
  #+end_src


* Diable smartparens in some modes
** We don't need smartparens in RE builder
   #+begin_src emacs-lisp
     (add-to-list 'sp-ignore-modes-list 'reb-mode)
   #+end_src


* Configure smartparens for html/xml
** Use smartparens navigating around html/xml tags as well
  #+begin_src emacs-lisp
    (sp-with-modes '(web-mode sgml-mode nxml-mode apache-mode)
      (sp-local-pair "<" ">"))

    (add-to-list 'sp-navigate-consider-sgml-tags 'web-mode)
    (add-to-list 'sp-navigate-consider-sgml-tags 'nxml-mode)
    (add-to-list 'sp-navigate-consider-sgml-tags 'apache-mode)
  #+end_src

** Treat expression with same opening and closing delimiter as sexp
  #+begin_src emacs-lisp
    (add-to-list 'sp-navigate-consider-stringlike-sexp 'web-mode)
  #+end_src

** Wrapping with tags in web-mode
  #+begin_src emacs-lisp
    (sp-local-tag '(sgml-mode web-mode html-mode) "<" "<_>" "</_>" :transform 'sp-match-sgml-tags)
  #+end_src


* Do not add autopair "'" if after a word
  #+begin_src emacs-lisp
    (sp-pair "'" nil :unless '(sp-point-after-word-p))
  #+end_src



* Do not autopair "`" and "'" in lisp buffer
  #+begin_src emacs-lisp
    (sp-local-pair '(emacs-lisp-mode lisp-mode scheme-mode lisp-interaction-mode)
                   "`" "'"
                   :when '(sp-in-string-p sp-in-comment-p))

    (sp-local-pair '(emacs-lisp-mode lisp-mode scheme-mode lisp-interaction-mode)
                   "'" nil
                   :actions nil)
  #+end_src


* Do not autoescape string
  #+begin_src emacs-lisp
    (setq sp-autoescape-string-quote nil)
  #+end_src


* Display configuration for smartparens
  #+begin_src emacs-lisp
    (setq sp-highlight-pair-overlay nil)
    (setq sp-highlight-wrap-overlay nil)
    (setq sp-highlight-wrap-tag-overlay nil)
  #+end_src


* Always skip closing parenthesis
  #+begin_src emacs-lisp
    (setq sp-autoskip-closing-pair 'always)
  #+end_src


* Keybindings for navigating around sexps using smartparens
  #+begin_src emacs-lisp
    (define-key sp-keymap (kbd "C-M-f") 'sp-forward-sexp)
    (define-key sp-keymap (kbd "C-M-b") 'sp-backward-sexp)

    (define-key sp-keymap (kbd "C-M-n") 'sp-next-sexp)
    (define-key sp-keymap (kbd "C-M-p") 'sp-previous-sexp)

    (define-key sp-keymap (kbd "C-M-u") 'sp-up-sexp)
    (define-key sp-keymap (kbd "C-M-S-u") 'sp-backward-up-sexp)
    (define-key sp-keymap (kbd "C-M-d") 'sp-down-sexp)
    (define-key sp-keymap (kbd "C-M-S-d") 'sp-backward-down-sexp)
  #+end_src


* Keybindings for manipulating sexps using smartparens
  #+begin_src emacs-lisp
    (define-key sp-keymap (kbd "C-M-k") 'sp-kill-sexp)
    (define-key sp-keymap (kbd "C-M-S-k") 'sp-backward-kill-sexp)
    (define-key sp-keymap (kbd "C-M-;") 'sp-kill-hybrid-sexp)

    (define-key sp-keymap (kbd "C-M-r") 'sp-rewrap-sexp)
    (define-key sp-keymap (kbd "C-M-S-r") 'sp-swap-enclosing-sexp)

    (define-key sp-keymap (kbd "C-M-w") 'sp-copy-sexp)
    (define-key sp-keymap (kbd "C-M-S-w") 'sp-backward-copy-sexp)

    (define-key sp-keymap (kbd "C-M-j") 'sp-join-sexp)
    (define-key sp-keymap (kbd "C-M-S-j") 'sp-split-sexp)
    (define-key sp-keymap (kbd "C-M-S-t") 'sp-transpose-sexp)

    (define-key sp-keymap (kbd "M-S-<delete>") 'sp-unwrap-sexp)
    (define-key sp-keymap (kbd "M-S-<backspace>") 'sp-backward-unwrap-sexp)

    (define-key sp-keymap (kbd "C-M-s") 'sp-splice-sexp)
    (define-key sp-keymap (kbd "C-{") 'sp-splice-sexp-killing-forward)
    (define-key sp-keymap (kbd "C-}") 'sp-splice-sexp-killing-backward)
    (define-key sp-keymap (kbd "C-M-|") 'sp-splice-sexp-killing-around)

    (define-key sp-keymap (kbd "C-M->") 'sp-forward-slurp-sexp)
    (define-key sp-keymap (kbd "C-M-<") 'sp-backward-slurp-sexp)
    (define-key sp-keymap (kbd "C-M-.") 'sp-forward-barf-sexp)
    (define-key sp-keymap (kbd "C-M-,") 'sp-backward-barf-sexp)

    (define-key sp-keymap (kbd "<C-left_bracket>") 'sp-select-previous-thing)
    (define-key sp-keymap (kbd "C-]") 'sp-select-next-thing)

    (define-key sp-keymap (kbd "C->") 'sp-add-to-next-sexp)
    (define-key sp-keymap (kbd "C-<") 'sp-add-to-previous-sexp)
  #+end_src


* Highlight matching parenthesis
** Enable highlighting
  #+begin_src emacs-lisp
    (show-paren-mode t)
  #+end_src

** Show matching paranthesis immediately
   #+begin_src emacs-lisp
     (setq show-paren-delay 0)
   #+end_src

** Highlight only the paranthesis
   #+begin_src emacs-lisp
     (setq show-paren-style 'parenthesis)
   #+end_src

** Custom colors for parenthesis
   #+begin_src emacs-lisp
     (set-face-attribute 'show-paren-mismatch nil :foreground "white" :background "red")
   #+end_src
