;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	backward-kill-line
	backward-sexp
	browse-kill-ring
	cut-line-or-region
	dabbrev-expand
	delete-horizontal-space
	eval-print-last-sexp
	forward-sexp
	isearch-abort
	jedi:dot-complete
	kill-sentence
	overwrite-mode
	phi-rectangle-kill-ring-save
	sp--self-insert-command
	sp-backward-down-sexp
	sp-backward-sexp
	sp-backward-unwrap-sexp
	sp-backward-up-sexp
	sp-down-sexp
	sp-forward-sexp
	sp-forward-slurp-sexp
	sp-kill-sexp
	sp-unwrap-sexp
	st2-like-beginning-of-line
	tern-ac-dot-complete
	transpose-words
	wdired-finish-edit
	yas-expand
	))

(setq mc/cmds-to-run-once
      '(
	help-for-help
	))
