;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        autopair-insert-opening
        autopair-insert-or-skip-quote
        backward-kill-line
        backward-sexp
        browse-kill-ring
        c-electric-colon
        c-electric-delete-forward
        c-electric-semi&comma
        complete-symbol
        completion-at-point
        copy-line-or-region
        cut-line-or-region
        dabbrev-expand
        delete-horizontal-space
        down-list
        eval-and-replace
        eval-last-sexp
        eval-print-last-sexp
        forward-sentence
        forward-sexp
        increment-integer-at-point
        jedi:dot-complete
        kill-sentence
        kill-sexp
        mark-sexp
        python-indent-electric-colon
        repeat
        sp--self-insert-command
        sp-backward-down-sexp
        sp-backward-kill-sexp
        sp-backward-sexp
        sp-backward-unwrap-sexp
        sp-backward-up-sexp
        sp-down-sexp
        sp-forward-sexp
        sp-forward-slurp-sexp
        sp-kill-sexp
        sp-rewrap-sexp
        sp-unwrap-sexp
        st2-like-beginning-of-line
        tern-ac-dot-complete
        transpose-words
        wdired-finish-edit
        yas-expand
        ))

(setq mc/cmds-to-run-once
      '(
        describe-key
        help-for-help
        isearch-forward-regexp
        keyboard-escape-quit
        mouse-set-region
        smex
        sp-transpose-sexp
        wgrep-change-to-wgrep-mode
        wgrep-finish-edit
        ))
