;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	dabbrev-expand
	eval-print-last-sexp
	isearch-abort
	jedi:dot-complete
	overwrite-mode
	phi-rectangle-kill-ring-save
	sp--self-insert-command
	sp-down-sexp
	sp-forward-sexp
	sp-forward-slurp-sexp
	sp-kill-sexp
	st2-like-beginning-of-line
	tern-ac-dot-complete
	transpose-words
	wdired-finish-edit
	yas-expand
	))

(setq mc/cmds-to-run-once
      '())
